service: ae
runtime: python
vm: true
entrypoint: gunicorn -b :$PORT main:app

manual_scaling:
  instances: 1

runtime_config:
  python_version: 3

resources:
  cpu: .5
  memory_gb: 0.18
  disk_size_gb: 10