# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeiot', '0004_auto_20161004_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='source_code',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
